
export DOTFILES_DIR=/home/kaylier/.dotfiles

export PATH=${PATH}:${DOTFILES_DIR}/bin

export GNUPGHOME=${HOME}/.config/gnupg

export XDG_DESKTOP_DIR=${HOME}
export XDG_DOWNLOAD_DIR=${HOME}/download
export XDG_TEMPLATES_DIR=${DOTFILES_DIR}/template
export XDG_DOCUMENTS_DIR=${HOME}/document
export XDG_MUSIC_DIR=${HOME}/music
export XDG_PICTURES_DIR=${HOME}/image
export XDG_VIDEOS_DIR=${HOME}/film

